version: '3'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "P@ssw0rd"
      MYSQL_DATABASE:  "development"
      TZ: "Asia/Tokyo"
